language: python

# Default Python version is usually 2.7
python: 3.7

# Install ruby to get gem command
before_install:
    - python --version
    - pip install -U pip
    - pip install -U pytest
    - pip install codecov
    - sudo apt-add-repository -y ppa:brightbox/ruby-ng
    - sudo apt-get -y update
    - sudo apt-get -y install ruby-full

before_script:
    - gem install awesome_bot


install:
    - pip3 install -r requirements.txt
    #- pip3 install coveralls

script:
    pytest
     # - awesome_bot README.md --allow-dupe --allow-redirect
     # # Dynamic Programming Tests
     # - python Algorithm_tests/dynamic_programming_tests/knapsack_tests/knapsack_bottomup_test.py
     # - python Algorithm_tests/dynamic_programming_tests/sequence_alignment/sequence_alignment_test.py
     # - python Algorithm_tests/dynamic_programming_tests/weighted_interval_scheduling/weighted_interval_scheduling_test.py
     
     # # Graph Theory Tests
     # - python Algorithm_tests/graphtheory_tests/bellman_ford_test.py
     # - python Algorithm_tests/graphtheory_tests/kahn_topological_ordering_test.py
     # - python Algorithm_tests/graphtheory_tests/Djikstra/djikstra_heap_test.py
     # - python Algorithm_tests/graphtheory_tests/Djikstra/djikstra_naive_test.py
     # - python Algorithm_tests/graphtheory_tests/kruskal_unionfind_test.py
     # - python Algorithm_tests/graphtheory_tests/prims_algorithm_test.py
     # - python Algorithm_tests/graphtheory_tests/BFS_test.py
     # - python Algorithm_tests/graphtheory_tests/DFS_test.py
     
     # # Math tests
     # - python Algorithm_tests/other_tests/test_binarysearch.py
     # - python Algorithm_tests/math_tests/intersection_test.py
     # - python Algorithm_tests/math_tests/union_test.py
     
     # # Cryptography tests
     # - python Algorithm_tests/cryptology_tests/ceasar_test.py
     
     # # "Other" tests
     # - python Algorithm_tests/other_tests/test_medianmaintenance.py
     # - python Algorithm_tests/other_tests/test_intervalscheduling.py
     
     # # Sorting tests
     # - python Algorithm_tests/sorting_tests/test_sorting.py

after_success:
    #- coveralls