language: python

# Default Python version is usually 2.7
python: 3.7

# Install ruby to get gem command
before_install:
  - sudo apt-add-repository -y ppa:brightbox/ruby-ng
  - sudo apt-get -y update
  - sudo apt-get -y install ruby-full

#before_install:
#    - cd Algorithm_tests/sorting_tests
# Install awesome_bot for README.md broken link checking

before_script:
  - gem install awesome_bot

script:
     - awesome_bot README.md --allow-dupe --allow-redirect
     - python Algorithm_tests/sorting_tests/test_sorting.py
     - python Algorithm_tests/graphtheory_tests/bellman_ford_test.py
     - python Algorithm_tests/other_tests/test_binarysearch.py
     - python Algorithm_tests/math_tests/intersection_test.py
     - python Algorithm_tests/math_tests/union_test.py
     - python Algorithm_tests/cryptology_tests/ceasar_test.py
     - python Algorithm_tests/other_tests/test_intervalscheduling.py
